"""users table

Revision ID: c1d07eab0c57
Revises: 
Create Date: 2022-11-02 13:56:11.983976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d07eab0c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('User', sa.Column('name', sa.String(length=60), nullable=True))
    op.add_column('User', sa.Column('surname', sa.String(length=60), nullable=True))
    op.add_column('User', sa.Column('password', sa.String(length=500), nullable=True))
    op.add_column('User', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('User', sa.Column('telephone', sa.String(length=15), nullable=True))
    op.add_column('User', sa.Column('info', sa.String(length=70), nullable=True))
    op.add_column('User', sa.Column('address', sa.String(length=320), nullable=True))
    op.add_column('User', sa.Column('date_registration', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'User', ['email'])
    op.create_unique_constraint(None, 'User', ['telephone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'date_registration')
    op.drop_column('User', 'address')
    op.drop_column('User', 'info')
    op.drop_column('User', 'telephone')
    op.drop_column('User', 'email')
    op.drop_column('User', 'password')
    op.drop_column('User', 'surname')
    op.drop_column('User', 'name')
    op.drop_column('User', 'id')
    # ### end Alembic commands ###
